### ISSUE TITLE
What is "self.super" ?

### ISSUE THREAD

**Issue by marceaupatu123** [TheNexusAvenger/Nexus-Admin#10]
https://github.com/TheNexusAvenger/Nexus-Admin/blob/692da3b0f0f62dd268c22db555413fd631eed9cc/src/IncludedCommands/BasicCommands/sword.lua#L33

I see it in almost every commands but what is super ? I didn't find it on the documentation.

**Comment by TheNexusAvenger** [comment]
`super` is a feature of Nexus Instance for inheritance.
https://thenexusavenger.github.io/Nexus-Instance/getting-started/classes/nexusobject/#nexusobjectsuper
