### ISSUE TITLE
How can I load setup nexus to search for custom commands elsewhere than the loader children ?

### ISSUE THREAD

**Issue by marceaupatu123** [TheNexusAvenger/Nexus-Admin#12]
I actually use Rojo and I can't put scripts into others scripts in vscode (of course), what can I do ?

**Comment by TheNexusAvenger** [comment]
Rojo supports `init.*.lua` files, which specifies that the folder the script is in should be a script in Roblox with the contents of that file. [This is covered in the Rojo sync details doc](https://rojo.space/docs/v7/sync-details/#scripts). Examples with this for Nexus Admin exist in [Nexus Battles](https://github.com/TheNexusAvenger/Nexus-Battles/tree/master/src/ServerScriptService/NexusAdminLoader) and [The Witching Hour Remastered](https://github.com/TheNexusAvenger/Roblox-The-Witching-Hour-Remastered/tree/master/src/ServerScriptService/NexusAdminLoader).
