### ISSUE TITLE
misspelling of ServerScriptService in the docs

### ISSUE THREAD

**Issue by xs4u** [TheNexusAvenger/Nexus-Admin#13]
https://github.com/TheNexusAvenger/Nexus-Admin/blob/master/docs/loading.md

--Require Nexus Admin (not the MainModule)
local NexusAdmin = require(game.**ServerScriptServicee.**MainModule.NexusAdmin)

**Comment by xs4u** [comment]
for some reason, can't add labels

**Comment by TheNexusAvenger** [comment]
That is a bit embarrassing, especially in code. I've corrected the typo.
