### ISSUE TITLE
Bug: Types file link is incorrect

### ISSUE THREAD

**Issue by xs4u** [TheNexusAvenger/Nexus-Admin#14]
https://github.com/TheNexusAvenger/Nexus-Admin/blob/typing-refactor/src/Types.lua is gone, it seems to be still linked at https://github.com/TheNexusAvenger/Nexus-Admin/blob/master/docs/api.md though

**Comment by xs4u** [comment]
nvm the link is just weird, it seems to exist, though the link is incorrect

**Comment by TheNexusAvenger** [comment]
Fixed. Thanks.
