### ISSUE TITLE
Usage Command Typo and Suggestion

### ISSUE THREAD

**Issue by landenjw** [TheNexusAvenger/Nexus-Admin#15]
In the usage command it says to use backslash to open the Cmdr command line. As of a few versions ago it was changed to use F2 by default, but it still says to use backslash in the usage command.

Separate Suggestion: Because the command by default is called 'usage' you should make the window title that it opens named 'Usage' instead of 'About'. Personally, I would just rename the 'Usage' command to about.
![image](https://github.com/TheNexusAvenger/Nexus-Admin/assets/45887470/3ac54079-664d-4269-b57d-584c5de8c0f3)

**Comment by TheNexusAvenger** [comment]
> In the usage command it says to use backslash to open the Cmdr command line. As of a few versions ago it was changed to use F2 by default, but it still says to use backslash in the usage command.

Thanks. I've updated that command to grab the activation key.

> Separate Suggestion: Because the command by default is called 'usage' you should make the window title that it opens named 'Usage' instead of 'About'. Personally, I would just rename the 'Usage' command to about.

I've changed the command to default to `about` with the alias of `usage` (to keep backward compatibility. Thanks for the idea.

Both of these are up with V.2.7.3.
