### ISSUE TITLE
Types ModuleScript typing issue & new :about Command Level issue

### ISSUE THREAD

**Issue by ezekieltem** [TheNexusAvenger/Nexus-Admin#16]
2 Seperate issues that I am combining into 1 as to not create multiple issue requests.

## Types ModuleScript Issue:
In the MessagesServer Type in the Types ModuleScript the :DisplayNotification() typing is inaccurate.
The current typing
`DisplayNotification: (self: MessagesClient, TopText: string, Message: string, DisplayTime: number?) -> ()`
`self` declared as `MessagesClient` causes the Studio Autocomplete to not display `DisplayNotification` as an option;
![image](https://github.com/ezekieltem/private-scripts-of-mine/assets/82738698/7102d924-e8aa-4bcc-8dad-a1b69fc5e202)
In the actual function for `:DisplayNotification` in `ServerMessages` shows that it takes a `Player` argument as the first argument, the typing for this however does not.
![image](https://github.com/ezekieltem/private-scripts-of-mine/assets/82738698/c3024eb5-5daa-4001-81ec-2d0204c14106)
This in reality, is only an issue for developers.

## New :about issue
As of v2.7.3 `:usage` was replaced with `:about` in the NexusAdminMainModule, no change was reflected across to the NexusAdminLoader,
*(other entrees removed for ease of taking screenshot)*
![image](https://github.com/ezekieltem/private-scripts-of-mine/assets/82738698/e759f38d-7606-4195-acf8-e30851022b8d)
And `:about` receives the AdministrativeLevel instead of carrying over its previous overridden value when it was `:usage`

**Comment by TheNexusAvenger** [comment]
Just a heads up - I can't see the images. By the URLs, my guess is they were copied from a private repository instead of reuploaded publicly. Because of this, I'm leaving this open until I can confirm I handled everything.

> In the MessagesServer Type in the Types ModuleScript the :DisplayNotification() typing is inaccurate.

Looks like I copied the client version but didn't correct it for the server. That should be correct now. (https://github.com/TheNexusAvenger/Nexus-Admin/commit/e45d4d672c2e5c335028400cd1817e9ee7bc8da3)

> As of v2.7.3 `:usage` was replaced with `:about` in the NexusAdminMainModule, no change was reflected across to the NexusAdminLoader,

Oof... I didn't realize how breaking of a change that would be. I've rolled back `about` being default in favor of the original `usage` to ensure it picks up the correct permissions for earlier loaders. Sorry about that.

**Comment by ezekieltem** [comment]
> Just a heads up - I can't see the images. By the URLs, my guess is they were copied from a private repository instead of reuploaded publicly. Because of this, I'm leaving this open until I can confirm I handled everything.

Ah sorry, I haven't really ever made an issue on github before here are the images (hopefully uploaded correctly this time) in the order they were in the original post
![255041984-7102d924-e8aa-4bcc-8dad-a1b69fc5e202](https://github.com/TheNexusAvenger/Nexus-Admin/assets/82738698/cb30471f-a8fb-479c-b791-32027290fbba)
![255042502-c3024eb5-5daa-4001-81ec-2d0204c14106](https://github.com/TheNexusAvenger/Nexus-Admin/assets/82738698/0d45deb3-a581-4095-b21e-050156b0595e)
![255043148-e759f38d-7606-4195-acf8-e30851022b8d](https://github.com/TheNexusAvenger/Nexus-Admin/assets/82738698/bf0977bf-2d3e-4a92-826b-a1976cd7d3dd)

**Comment by TheNexusAvenger** [comment]
In that case, I think I got everything. Please re-open this issue if something was missed.
