### ISSUE TITLE
Activation key

### ISSUE THREAD

**Issue by carambaritoyt** [TheNexusAvenger/Nexus-Admin#6]
I cant set a custom activation key the admin just dont respond with that key  
NexusAdminClient.Cmdr:SetActivationKeys({Enum.KeyCode.LeftControl})

**Comment by TheNexusAvenger** [comment]
This use case isn't supported at the moment. What I imagine happens is you call `SetActivationKeys`, and then the loader calls `SetActivationKeys` as default. Pull requests are open to provide a solution for this.

**Comment by carambaritoyt** [comment]
So what i can do?

**Comment by TheNexusAvenger** [comment]
The ideas I have are:
1. Add the activation key to the configuration.
2. Allow `LocalScript`s to call `SetActivationKeys` for what they need. If it is called, Nexus Admin should ignore this.

This use case isn't a priority for me to implement. A pull request with one of these changes is probably the path forward.

**Comment by TheNexusAvenger** [comment]
V.2.3.5 is now out with this change made in Pull Request #7.
